FIRSTCRM/FIRSTCRM/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from FIRSTCRM import view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', view.index),#进入主页
    # url(r'^registers/$', view.registers),#注册
    # url(r'^register/$', view.register),#注册
    # url(r'^check_code.html$', view.check_code),# 验证码 校对
    url(r'^accounts/login/', view.acc_login),#全局login
    url(r'^account/logout/', view.acc_logout,name='acc_logouta'),#全局logout django logout 默认跳转到accounts/login
    url(r'^modify/(\d+)', view.modify,name='acc_modify'),#全局logout django logout 默认跳转到accounts/login
    url(r'^crm/', include('crm.urls')),#客户库
    url(r'^student/', include('student.urls')),#学员
    url(r'^teacher/', include('teacher.urls')),#讲师
    url(r'^sales/', include('sales.urls')),#销售
    url(r'^financial/', include('financial.urls')),#财务
    url(r'^king_admin/', include('king_admin.urls')),#自定义admin
    url(r'^kingadmin/', include('kingadmin.urls')),#自定义admin

]

FIRSTCRM/crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from crm import views
urlpatterns = [
    # url(r'^$', views.index,name='sales_index'),#销售首页
    url(r'^registers.html$', views.registers),#注册
    url(r'^register.html$', views.register),#注册
    url(r'^check_code.html$', views.check_code),# 验证码 校对
    url(r'^customers/$', views.customers, name="customers"),#客户库
    url(r'^customer/(\d+)/enrollment/$', views.enrollment, name="enrollment"),#报名流程一 下一步
    url(r'^contract_prompt/$', views.contract_prompt, name="contract_prompt"),#报名提示
    url(r'^customer/registration/(\d+)/(\w+)/$', views.stu_registration, name="stu_registration"),#报名流程二 学员签同合
    # url(r'^contract_review/(\d+)/$', views.contract_review, name="contract_review"),#报名流程三  审核
    # url(r'^enrollment_rejection/(\d+)/$', views.enrollment_rejection, name="enrollment_rejection"),#报名流程三 驳回
    # url(r'^payment/(\d+)/$', views.payment, name="payment"),#报名流程四    缴费
    #url(r'^customer/registration/(\d+)-(\d+)-(\d+)/$', views.stu_registration_l, name="stu_registration_l"),#报名流程二 学员签同合
    # url(r'^my_class_list/$', views.my_class_list, name="my_class_list"),#班级
]

FIRSTCRM/kingadmin/urls.py
from django.conf.urls import url,include
from kingadmin import views

urlpatterns = [

    url(r'^login/$', views.acc_login, name="acc_login"),
    url(r'^logout/$', views.acc_logout, name="acc_logout"),
    url(r'^(\w+)/(\w+)/change/(\d+)/password/$', views.password_reset_form, name='password_reset'),
    url(r'^account/password_reset/$', views.personal_password_reset, name='personal_password_reset'),

    url(r'^$', views.app_index, name="table_index"),  # 显示所有注册的表
    url(r'^(\w+)/$', views.app_tables, name="app_tables"),  # 显示每个app里所有注册的表
    url(r'^(\w+)/(\w+)/$',views.display_table_list,name="table_list"), #显示每个表的数据
    url(r'^(\w+)/(\w+)/add/$', views.table_add, name="table_add"),
    url(r'^(\w+)/(\w+)/change/(\d+)/$', views.table_change, name="table_change"),
    #
    url(r'^(\w+)/(\w+)/delete/(\d+)/$', views.table_del, name="table_del"),


]

FIRSTCRM/student/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from student import views
urlpatterns = [
    url(r'^$', views.index,name='stu_index'),#学员首页
    url(r'^my_course/$', views.my_course,name='my_course'),#班级
    url(r'^studyrecords/(\d+)/$', views.studyrecords,name='studyrecords'),#个人作业列表
    url(r'^homework_detail/(\d+)/(\d+)/$', views.homework_detail,name='homework_detail'),#作业详情

]

FIRSTCRM/crm/models.py
from django.db import models
from django.contrib.auth.models import User #帐户模块
from django.contrib.auth.models import (BaseUserManager,AbstractBaseUser,PermissionsMixin)
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from django.contrib.auth.models import Permission
# Create your models here.

#客户表
class Customer(models.Model):
    '''客户表'''
    #           blank   Django admin 创建可以为空 // null 数据库中可以为空
    name=models.CharField(max_length=32,blank=True,null=True,help_text="报名后修改为真实姓名!")
    qq=models.CharField(max_length=64,unique=True)#unigue 唯一值
    qq_name=models.CharField(max_length=64,blank=True,null=True)#qq昵称
    phone=models.CharField(max_length=64,blank=True,null=True,verbose_name='手机号')#手机号
    id_num=models.CharField(max_length=64,blank=True,null=True,verbose_name='身份证号')#身份证号
    email=models.EmailField(max_length=64,blank=True,null=True,verbose_name='邮箱')#email
    sex_choices=((0,'保密'),(1,'男'),(2,'女'))
    sex=models.SmallIntegerField(choices=sex_choices,default=0,verbose_name='性别')
    source_choices =((0,'转介绍'),(1,'QQ群'),(2,'官网'),(3,'百度推广'),(4,'51CTO'),(5,'知乎'),(6,'市场推广'))
    source=models.SmallIntegerField(choices=source_choices)#选择来源
    referral_from=models.CharField(verbose_name='转介绍人QQ',max_length=64,blank=True,null=True)
    tags=models.ManyToManyField('Tag',blank=True,null=True)#标签多对多
    consult_course=models.ForeignKey('Course',verbose_name='咨询课程',related_name='customer',on_delete=models.CASCADE)#外键课程表
    status_choices = ((0,'已报名'),(1,'未报名'),(2,'已退学'))
    status = models.SmallIntegerField(choices=status_choices,default=1)#学员状态
    content=models.TextField()#咨询内容
    consultant=models.ForeignKey('UserProfile',verbose_name='课程顾问',related_name='customer',on_delete=models.CASCADE)#课程顾问
    date=models.DateTimeField(auto_now_add=True)#记录时间
    memo=models.TextField(blank=True,null=True)#备注
    def __str__(self):
        return self.qq
    class Meta:
        verbose_name='客户表'
        verbose_name_plural='客户表'

    def clean_status(self):
        status = self.cleaned_data['status']
        if self.instance.id == None:  # add form
            if status == "signed":
                raise forms.ValidationError(("必须走完报名流程后，此字段才能改名已报名"))
            else:
                return status

        else:
            return status
    def clean_consultant(self):
        consultant = self.cleaned_data['consultant']

        if self.instance.id == None :#add form
            return self._request.user

        elif consultant.id != self.instance.consultant.id:
            raise forms.ValidationError(('Invalid value: %(value)s 课程顾问不允许被修改,shoud be %(old_value)s'),
                                         code='invalid',
                                         params={'value': consultant,'old_value':self.instance.consultant})
        else:
            return consultant

#标签表
class Tag(models.Model):
    name=models.CharField(unique=True,max_length=32)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='标签表'
        verbose_name_plural='标签表'

##跟进记录表
class CustomerFollowUp(models.Model):
    '''跟进记录表'''
    customer=models.ForeignKey('Customer',verbose_name='客户',related_name='customerfollowup',on_delete=models.CASCADE)#外键  跟进的客户
    content=models.TextField(verbose_name='跟进内容')
    consultant=models.ForeignKey('UserProfile',verbose_name='跟进人员',related_name='customerfollowup',on_delete=models.CASCADE)#跟进人员
    date=models.DateTimeField(auto_now_add=True)#时间
    intention_choices=((0,'2周内报名'),(1,'1个月内报名'),(2,'近期无报名计划'),(3,'已经在其它机构报名'),(4,'已报名'),(5,'已拉黑'))
    intention=models.SmallIntegerField(choices=intention_choices)#选择意向
    #date = models.DateTimeField(auto_now_add=True)#记录时间
    def __str__(self):
        #return "<%s:%s>"%(self.customer.qq,self.intention)#返回客户的QQ,意向
        return '%s'%self.customer#返回客户的QQ,意向
    class Meta:
        verbose_name='跟进记录表'
        verbose_name_plural='跟进记录表'

#课程表
class Course(models.Model):
    '''课程表'''
    name=models.CharField(max_length=64,unique=True)
    price=models.PositiveSmallIntegerField()#学费 正数
    period=models.PositiveSmallIntegerField(verbose_name='周期(月)')#周期
    outling=models.TextField()#课程大纲


    def __str__(self):
        return self.name
    class Meta:
        verbose_name='课程表'
        verbose_name_plural='课程表'

#校区
class Branch(models.Model):
    '''校区表'''
    name=models.CharField(max_length=128,unique=True)#校区名
    addr=models.CharField(max_length=128)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='校区表'
        verbose_name_plural='校区表'

#班级表
class ClassList(models.Model):
    '''班级表'''
    branch=models.ForeignKey('Branch',verbose_name='校区',related_name='classlist',on_delete=models.CASCADE)#校区
    course=models.ForeignKey('Course',verbose_name='课程',related_name='classlist',on_delete=models.CASCADE)#关联课程
    contract=models.ForeignKey('ContractTemplate',blank=True,null=True,default=1,verbose_name='合同',related_name='classlist',on_delete=models.CASCADE)#合同表
    class_type_choices=((0,"面授(脱产)"),(1,"面授(周末)"),(2,"网络班"))
    class_type=models.SmallIntegerField(choices=class_type_choices,verbose_name='班级类型')
    semester=models.PositiveSmallIntegerField(verbose_name='学期')
    teacher=models.ManyToManyField('UserProfile')#讲师 关联
    start_date=models.DateField(verbose_name='开班日期')#
    end_date=models.DateField(verbose_name='结业日期',blank=True,null=True)#
    def __str__(self):
        return '%s 校区: 课程：%s %s 第 %s 期'%(self.branch,self.course,self.get_class_type_display(),self.semester)#校区,课程,班级类型,学期
        #return '%s %s %s'%(self.branch,self.course,self.semester)#校区,课程,学期

    class Meta:
        unique_together=('branch','course','semester')#联合唯一 校区,课程,学期
        verbose_name='班级表'
        verbose_name_plural='班级表'

#课程上课记录表
class CourseRecord(models.Model):
    '''课程上课记录表'''
    from_class=models.ForeignKey('ClassList',verbose_name='班级',related_name='courserecord',on_delete=models.CASCADE)#班级名
    day_num=models.PositiveSmallIntegerField(verbose_name='第几节(天)')
    teacher=models.ForeignKey("UserProfile",verbose_name='讲师',related_name='courserecord',on_delete=models.CASCADE)#讲师
    has_homework=models.BooleanField(default=True,verbose_name='是否有作业')#是否有作业
    homework_title=models.CharField(max_length=128,blank=True,null=True,verbose_name='作业名称')#作业名称
    homework_content=models.TextField(blank=True,null=True,verbose_name='作业内容')#作业内容
    outline= models.TextField(verbose_name='本节课程大纲')
    date=models.DateField(auto_now_add=True, verbose_name="上课日期")#上课时间
    def __str__(self):
        return '班级:%s第 %s 节'%(self.from_class,self.day_num)#班级,节数


    class Meta:
        unique_together=('from_class','day_num')##班级,节数  联合唯一
        verbose_name='课程上课记录表'
        verbose_name_plural='课程上课记录表'

#学习记录表
class StudyRecord(models.Model):
    '''学习记录表'''
    student=models.ForeignKey("Enrollment",verbose_name='报名学员',related_name='studyrecord',on_delete=models.CASCADE)#外键关联  报名表
    course_record=models.ForeignKey('CourseRecord',verbose_name='上课记录',related_name='studyrecord',on_delete=models.CASCADE)#外键关联 上课记录表
    attendance_choices=((0,'已签到'),(1,'迟到'),(2,'缺勤'),(3,'早退'))#出勤状态
    attendance=models.SmallIntegerField(choices=attendance_choices,default=0)#出勤状态
    score_choices=((100,'A+'),(90,'A'),(85,'B+'),(80,'B'),(75,'B-'),(70,'C+'),(60,'C'),(40,'C-'),(-50,'D'),(-100,'COPY'),(0,'N/A'))#分数等级
    score=models.SmallIntegerField(choices=score_choices,default=0,blank=True,null=True)#分数等级成绩
    memo=models.TextField(blank=True,null=True)#备注
    date=models.DateField(auto_now_add=True)#日期

    def __str__(self):
        #print(self,'<----student')
        # return '%s %s %s'%(self.student,self.course_record,self.score)#学员,课程,成绩,,
        #return '%s %s %s'%(self.student.consultant.name,self.course_record.from_class,self.score)#学员,课程,成绩,,
        return '%s %s %s'%(self.student.customer.name,self.course_record.from_class,self.score)#学员,课程,成绩,,

    class Meta:
        unique_together=('student','course_record')#
        verbose_name='学习记录表'
        verbose_name_plural='学习记录表'

#报名表
class Enrollment(models.Model):
    '''报名\入学表'''
    customer=models.ForeignKey('Customer',verbose_name='客户',related_name='enrollment',on_delete=models.CASCADE)#客户  学员
    enrolled_class=models.ForeignKey('ClassList',verbose_name='所报班级',related_name='enrollment',on_delete=models.CASCADE)#班级->课程
    consultant=models.ForeignKey('UserProfile',verbose_name='课程顾问',related_name='enrollment',on_delete=models.CASCADE)#课程顾问
    contract_agreed=models.BooleanField(default=False,verbose_name="学员已同意合同条款")#合同
    contract_approved=models.BooleanField(default=False,verbose_name="合同已审核")#合同
    date=models.DateTimeField(auto_now_add=True)#时间,精确到时分秒
    contract_url=models.TextField(verbose_name='学员合同确认链接',null=True)

    def __str__(self):
        #return '%s %s'%(self.customer,self.enrolled_class)#返回学员所报班级课程
        return '%s  |学员：%s  '%(self.enrolled_class,self.customer.name)#返回学员所报班级课程

    class Meta:
        unique_together=('customer','enrolled_class')#学员,,班级课程
        verbose_name='报名表'
        verbose_name_plural='报名表'


#缴费记录
class Payment(models.Model):
    '''缴费记录'''
    customer=models.ForeignKey('Customer',verbose_name='缴费学员',related_name='payment',on_delete=models.CASCADE)#客户表 学员
    course=models.ForeignKey('Course',verbose_name='所报课程',related_name='payment',on_delete=models.CASCADE)#意向课程
    amount=models.PositiveIntegerField(verbose_name='数额',default=500)#所交金额
    consultant=models.ForeignKey('UserProfile',verbose_name='课程顾问',related_name='payment',on_delete=models.CASCADE)#办理人员 课程顾问
    date=models.DateTimeField("交款日期",auto_now_add=True)#时间

    def __str__(self):
        return '%s %s'%(self.customer,self.amount)#返回学员,金额
    class Meta:
        verbose_name='缴费记录'
        verbose_name_plural='缴费记录'


#创建用户和超级用户
class UserProfileManager(BaseUserManager):
    def create_user(self, email, name, password=None):
        """

FIRSTCRM/student/views.py
import json
import os
import time

from utils.permissions_2 import permission
# from utils.permissions import permission
# Create your views here.
from  django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponse

from FIRSTCRM import settings
from crm import models


#学员首页
@login_required
@permission.check_permission#权限装饰器
def index(request):
    user_id=request.user.id
    userinfo=models.UserProfile.objects.get(id=user_id)#帐号对象
    roles_list=userinfo.roles.all()#角色列表
    return  render(request,'student/index.html',locals())

#我的课程首页
@login_required
@permission.check_permission#权限装饰器
def my_course(request):
    return  render(request, 'student/my_course.html', locals())

#学习记录列表
@login_required
@permission.check_permission#权限装饰器
def studyrecords(request,enroll_obj_id):
    enroll_obj=models.Enrollment.objects.get(id=enroll_obj_id)
    return render(request,'student/studyrecords.html',locals())

#作业详情
@login_required
@permission.check_permission#权限装饰器
def homework_detail(request,enroll_obj_id,studyrecord_id):
    studyrecord_obj=models.StudyRecord.objects.get(id=studyrecord_id)#取学习记录 对象
    enroll_obj=models.Enrollment.objects.get(id=enroll_obj_id)#取班级对象
    print(request.FILES)
    #               作业根目录    班级ID      上课记录ID               学习记录ID
    homework_path="{base_dir}/{class_id}/{course_record_id}/{studyercord_id}/".format(
        base_dir=settings.HOMEWORK_DATA,
        class_id=studyrecord_obj.student.enrolled_class_id,
        course_record_id=studyrecord_obj.course_record_id,
        studyercord_id=studyrecord_obj.id
    )
    print('----->',studyrecord_obj.student.enrolled_class_id,studyrecord_obj.course_record_id,studyrecord_obj.id)
    if not os.path.isdir(homework_path):#没有目录
        os.makedirs(homework_path,exist_ok=True)#创建目录

    if request.method=="POST":#上传
        print("POST",request.POST)
        for k,v in request.FILES.items():#上传的文件
            with open('%s/%s'%(homework_path,v.name),'wb') as f:#chunk 写入文件
                for chunk in v.chunks():
                    f.write(chunk)


    file_lists=[]#已经上传的文件列表
    for file_name in os.listdir(homework_path):
        f_path='%s/%s'%(homework_path,file_name)#文件路径
        modify_time =time.strftime("%Y-%m-%d %H:%M:%S",time.gmtime(os.stat(f_path).st_mtime))#上传时间
        file_lists.append([file_name,os.stat(f_path).st_size,modify_time])#文件列表

    if request.method=="POST":#
        ret=False
        data=request.POST.get('data')
        if data:#如果有删除动作
            del_f_path="%s/%s"%(homework_path,data)#路径
            print(del_f_path,'=-=-=-=-=-=')
            os.remove(del_f_path)
            ret=True
            return HttpResponse(json.dumps(ret))
        print("POST",request.POST)
        return HttpResponse(json.dumps({"status":0,'mag':"上传完成！",'file_lists':file_lists}))
    return render(request,'student/homework_detail.html',locals())

FIRSTCRM/templates/student/homework_detail.html
{% extends 'master/index.html' %}
{% load stu_tags %}

{% block link %}

{% endblock %}
{% block page_content %}

    <div class="panel-default">
        <div class="row" style="margin-bottom: 20px">
            <ol class="breadcrumb">
                <li><a href="/student/">Home</a></li>
                <li><a href="/student/my_course/">我的课程</a></li>
                <li><a href="/student/studyrecords/{{ enroll_obj.id }}/">{{ enroll_obj.enrolled_class }}</a></li>
                <li><a href="#">第:{{ studyrecord_obj.course_record.day_num }}节</a></li>
            </ol>
        </div>
        {#    <div class="panel-heading">班级:{{ studyrecord_obj.course_record.from_class }} | 第:{{ studyrecord_obj.course_record.day_num }}节</div>#}
        <div class="panel-body">
            <h3>作业标题:{{ studyrecord_obj.course_record.homework_title }}</h3>
            <h4>作业详情:
                <pre>{{ studyrecord_obj.course_record.homework_content }}</pre>
            </h4>
            <h4>老师评语: {{ studyrecord_obj.memo }} </h4>
            <h4>本节成绩: {{ studyrecord_obj.score }} </h4>

        </div>
        <p>已经上传的文件:</p>
    <div class="row">
    <div class="col-xs-9 col-md-6">
        {% for file in file_lists %}
            <div class="right">
            {% for foo in file %}
                <a>{{ foo }}</a>  |
            {% endfor %}
                <span class="img_f hide">{{ file.0 }}</span>
                <a class="del_img">删除</a>
            </div>
            <br>
        {% endfor %}
    </div>
    </div>

        <p>请上传作业</p>
        <form action="{{ request.path }}" method="post" id="dropz" enctype="multipart/form-data" class="form-group dropzone">{% csrf_token %}

            <input type="hidden" name="file_id" ng-model="file_id" id="file_id"/>
        </form>


    </div>
{% endblock %}

{% block js %}

<script>

$('.del_img').click(function(){
        s=$(this);
        texts= s.parent().children("span").text();
{#        alert(texts);#}
        $.ajax({
            url:"{{ requset.path }}",
            type:"post",
            data:{"data":texts},
            headers:{'X-CSRFtoken':$.cookie('csrftoken')},
            success:function(arg){
                if(arg){
                    alert('删除成功!');
                    s.parent('div').addClass('hide');
                }
            }
        })
    });
    Dropzone.autoDiscover = false;
    appElement = document.querySelector('div .inmodal');
    myDropzone = new Dropzone("#dropz",  {
            url: "{{ request.path }}",//文件提交地址
            method: "post",  //也可用put
            paramName: "file", //默认为file
            maxFiles: 1,//一次性上传的文件数量上限
            maxFilesize: 2, //文件大小，单位：MB
            acceptedFiles: ".zip,.7z", //上传的类型
            addRemoveLinks: true,
            parallelUploads: 1,//一次上传的文件数量
            //previewsContainer:"#preview",//上传图片的预览窗口
            dictDefaultMessage: '请将作业压缩打包后上传',
            dictMaxFilesExceeded: "您最多只能上传1个文件！",
            dictResponseError: '文件上传失败!',
            dictInvalidFileType: "文件类型只能是*.zip,*.7z。",
            dictFallbackMessage: "浏览器不受支持",
            dictFileTooBig: "文件过大上传文件最大支持.",
            dictRemoveLinks: "删除",
            dictCancelUpload: "取消",
            init: function () {
                this.on("addedfile", function (file) {
                    //上传文件时触发的事件
                    document.querySelector('div .dz-default').style.display = 'none';
                });
                this.on("success", function (file, data) {
                    //上传成功触发的事件
                    console.log('ok');
                   // angular.element(appElement).scope().file_id = data.data.id;
                });
                this.on("error", function (file, data) {
                    //上传失败触发的事件
                    console.log('fail');
                    var message = '';
                    //lavarel框架有一个表单验证，
                    //对于ajax请求，JSON 响应会发送一个 422 HTTP 状态码，
                    //对应file.accepted的值是false，在这里捕捉表单验证的错误提示
                    if (file.accepted) {
                        $.each(data, function (key, val) {
                            message = message + val[0] + ';';
                        });
                        //控制器层面的错误提示，file.accepted = true的时候；
                        alert(message);
                    }
                });
                this.on("removedfile", function (file) {
                    //删除文件时触发的方法
                    //var file_id = angular.element(appElement).scope().file_id;
{#                    if (file_id) {#}
{#                        $.post('/admin/del/' + file_id, {'_method': 'DELETE'}, function (data) {#}
{#                            console.log('删除结果:' + data.message);#}
{#                        })#}
{#                    }#}
                   // angular.element(appElement).scope().file_id = 0;
                    document.querySelector('div .dz-default').style.display = 'block';
                });
            }

    });

</script>
{% endblock %}

FIRSTCRM/templates/student/index.html
{% extends 'master/index.html' %}

{% block page_content %}

<div class="panel-default">
    <div class="row" style="margin-bottom: 20px" >
        <ol class="breadcrumb">
         <li><a href="/student/">Home</a></li>
        </ol>
    </div>
    {% include 'include/panel-body.html' %}
</div>
{% endblock %}

FIRSTCRM/templates/student/my_course.html
{% extends 'master/index.html' %}
{% load stu_tags %}
{% block page_content %}


    <div class="panel-default">
{#        <div class="panel-heading">课程</div>#}
        <div class="row" style="margin-bottom: 20px" >
        <ol class="breadcrumb">
          <li><a href="/student/">Home</a></li>
          <li><a href="/student/my_course/">我的课程</a></li>
        </ol>
        </div>
        <div class="panel-body">
            <h3>{{ request.user }}</h3><!--对应的客户-->
            <table class="table table-striped table-responsive">
                <thead>
                <tr>
                    <th>课程名称</th>
                    <th>班级</th>
                    <th>开课日期</th>
                    <th>结业日期</th>
                    <th>课程进度</th>
                    <th>我的成绩</th>
                    <th>作业管理</th>
                </tr>
                </thead>
                <tbody>
                {% for enroll_obj in request.user.stu_account.enrollment_set.all %}
                    <tr>
                        <td>{{ enroll_obj.enrolled_class.course }}</td>
                        <td>s{{ enroll_obj.enrolled_class.semester }}</td>
                        <td>{{ enroll_obj.enrolled_class.start_date }}</td>
                        <td>{{ enroll_obj.enrolled_class.end_date }}</td>
                        <td>已上: {{ enroll_obj.enrolled_class.courserecord_set.all.count }} 节</td>
                        <td>{% get_score enroll_obj request.user.stu_account as score_data %}
                            {{ score_data.score__sum }}
                        </td>
                        <td><a href="{% url 'studyrecords' enroll_obj.id %}">作业管理</a></td>
                    </tr>

                {% endfor %}

                </tbody>
                <!--对应的客户qq-->

            </table>
        </div>

    </div>
{% endblock %}

FIRSTCRM/templates/student/studyrecords.html
{% extends 'master/index.html' %}
{% load stu_tags %}
{% block page_content %}


    <div class="panel-default">
{#        <div class="panel-heading">课程:{{ enroll_obj.enrolled_class }}</div>#}
        <div class="row" style="margin-bottom: 20px" >
        <ol class="breadcrumb">
          <li><a href="/student/">Home</a></li>
          <li><a href="/student/my_course/">我的课程</a></li>
          <li><a href="#">{{ enroll_obj.enrolled_class }}</a></li>
        </ol>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-responsive">
                <thead>
                <tr>
                    <th>课程节次</th>
                    <th>上课日期</th>
                    <th>是否有作业</th>
                    <th>作业标题</th>
                    <th>签到状态</th>
                    <th>我的成绩</th>
                    <th>作业详情</th>
                </tr>
                </thead>
                <tbody>
                {% for studyrecord in enroll_obj.studyrecord_set.all %}
                    <tr>
                        <td>{{ studyrecord.course_record.day_num }}</td>
                        <td>{{ studyrecord.course_record.date }}</td>
                        <td>{{ studyrecord.course_record.has_homework }}</td>
                        <td>{{ studyrecord.course_record.homework_title }}</td>
                        <td>{{ studyrecord.get_attendance_display }}</td>
                        <td>{{ studyrecord.get_score_display }}</td>
                        <td><a href="{% url 'homework_detail' enroll_obj.id studyrecord.id %}">作业管理</a></td>
                    </tr>

                {% endfor %}

                </tbody>


            </table>
        </div>

    </div>
{% endblock %}